name: Update dashboard data

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:
  push:
    paths:
      - "scripts/**"
      - ".github/workflows/update-data.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Fetch GitHub data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: Hardrivetech
        run: node scripts/fetch_github_data.js $GH_USERNAME

      - name: Commit and push if changed
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          if [ -n "$(git status --porcelain data/data.json)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/data.json
            git commit -m "chore: update dashboard data [skip ci]"
            git fetch origin $BRANCH
            git checkout -B $BRANCH origin/$BRANCH
            git push origin HEAD:$BRANCH
          else
            echo "No changes to commit."
          fi
